### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by General13K7** [MrKsey/torrserver-plus#3]
How to reset password on qbittorent?

**Comment by MrKsey** [comment]
Navigate to /docker/torrserver-plus/qBittorrent/config and edit the qBittorrent configuration file qBittorrent.conf.
Locate the entry of WebUI\Password_PBKDF2 and remove the entire line.
Save and close the file and restart container torrserver-plus.
You should then be able to login the WebUI using username admin and the default password adminadmin.

**Comment by MrKsey** [comment]
> How to reset password on qbittorent?

Navigate to /docker/torrserver-plus/qBittorrent/config and edit the qBittorrent configuration file qBittorrent.conf.
Locate the entry of WebUI\Password_PBKDF2 and remove the entire line.
Save and close the file and restart container torrserver-plus.
You should then be able to login the WebUI using username admin and the default password adminadmin.
